export enum ChunkType {
  ROUTE_HANDLER = 'ROUTE_HANDLER',
  SCHEMA_MODEL = 'SCHEMA_MODEL',
  EVENT_HANDLER = 'EVENT_HANDLER',
  SERVICE_METHOD = 'SERVICE_METHOD',
  CONFIGURATION = 'CONFIGURATION',
  README = 'README',
  FILE_SUMMARY = 'FILE_SUMMARY',
}
